//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlisverisTakipProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int Sepet1 { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<decimal> TotalFiyat { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
