//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlisverisTakipProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunSatislari
    {
        public int satisID { get; set; }
        public int urunID { get; set; }
        public Nullable<int> miktar { get; set; }
        public Nullable<decimal> toplamFiyat { get; set; }
        public Nullable<int> musteriID { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
