//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlisverisTakipProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.UrunSatislari = new HashSet<UrunSatislari>();
            this.Sepet = new HashSet<Sepet>();
        }
    
        public int urunID { get; set; }
        public string urunAdi { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> stokMiktari { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public Nullable<bool> populer { get; set; }
        public string stok { get; set; }
        public string resim { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunSatislari> UrunSatislari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}
